name: pofel_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-51.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  google_fonts: ^2.2.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.6
  equatable: ^2.0.3
  flutter_form_builder: ^7.0.0
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  image_picker: ^0.8.4+4
  firebase_storage_web: ^3.2.6
  shared_preferences: ^2.0.12
  google_nav_bar: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
