name: pofel_app
description: Epicka pofel apka.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+13

environment:
  sdk: ">=2.16.0-51.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  google_fonts: ^2.2.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.6
  equatable: ^2.0.3
  flutter_form_builder: ^7.0.0
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  image_picker: ^0.8.4+4
  firebase_storage_web: ^3.2.6
  shared_preferences: ^2.0.12
  google_nav_bar: ^5.0.5
  firebase_analytics: ^9.1.0
  firebase_messaging: ^11.2.6
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  rflutter_alert: ^2.0.4
  date_time_picker: ^2.1.0
  url_launcher: ^6.0.20
  maps_launcher: ^2.0.1
  reactive_forms: ^11.0.1
  open_file: ^3.2.1
  auto_size_text: ^3.0.0
  firebase_crashlytics: ^2.5.1
  cloud_functions: ^3.2.7
  firebase_dynamic_links: ^4.0.6
  flutterfire_ui: ^0.3.4
  flutter_share: ^2.0.0
  sizer: ^2.0.15
  expandable: ^5.0.1
  in_app_purchase: ^3.0.1
  twitter_login: ^4.0.1
  adapty_flutter: ^1.0.9
  galleryimage: ^1.1.0
  image_gallery_saver: ^1.7.1
  dio: ^4.0.4
  permission_handler: ^9.2.0
  qonversion_flutter: ^4.3.0
  cached_network_image: ^3.2.0
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/ios_pofel_logo.png" 
